### ISSUE TITLE
Redirects on Apache

### ISSUE THREAD

**Issue by ghost** [ecj2/kaku#1]
I'm not sure why, but I have to use relative redirects in my .htaccess:

```
RewriteEngine On
RewriteRule ^feed$ feed.php
RewriteRule ^post/(.*)$ ?post_url=$1
RewriteRule ^page/([0-9]+)$ ?page_number=$1
RewriteRule ^page/(.*)$ ?page_url=$1 [QSA]
```

Just thought it was worth noting.

**Comment by ecj2** [comment]
Thanks for letting me know. I'll look into it.

**Comment by ghost** [comment]
It may just be my setup. I'm running Debian. I have to do the same thing on my own site, no idea why. Both Debian 7 and 8.

**Comment by ecj2** [comment]
Okay. I'll do some local tests to see if I can reproduce the issue. I'll keep you updated.

**Comment by ecj2** [comment]
I was able to reproduce the issue locally. It seems to happen only when Kaku is installed on the root directory. I wrote the rewrites thinking Kaku would be installed in a sub-directory only. Oops.

I'll runs some tests for Nginx next, then I'll commit a fix. Thanks again for reporting this!
