### ISSUE TITLE
No default user created

### ISSUE THREAD

**Issue by ghost** [ecj2/kaku#18]
Not sure if I installed correctly. All I did was edit includes/configuration.php. After that, the front page said to login as admin with password password. My users table has no users, though (I will manually add one for now.)

**Comment by ghost** [comment]
It appears the reason is I'm using too old a version of PHP which doesn't have password_hash (we talked about this before.)

**Comment by ghost** [comment]
Solved using https://github.com/ircmaxell/password_compat

**Comment by ecj2** [comment]
Kaku requires PHP >= 5.5. You should be able to find PHP 5.5.x for your OS fairly easily, as 5.5.0 was released nearly three years ago (June 20, 2013). Interesting work around though!

**Comment by ghost** [comment]
I'm running Debian Wheezy on my server and I don't want to install from other repos or from source. But it's OK, I know Kaku requires PHP 5.5.
