### ISSUE TITLE
{%truncate%} not working on edited post

### ISSUE THREAD

**Issue by ghost** [ecj2/kaku#2]
I'm not sure if it's because I didn't include the tag initially or not, but when I add {%truncate%} it appears within the body of the post and doesn't truncate the post on the main page.

**Comment by ecj2** [comment]
When I revamped some of the code a while back, I accidentally removed {%truncate%} functionality and forgot to add it back again. This was fixed in 8173cfbde779a1622047aa053a7f350c8743883b though. Clone the latest commits and it should work for you.

**Comment by ghost** [comment]
Indeed, it does work.

**Comment by ecj2** [comment]
Good to hear it. By the way, you can edit the lure_text tag in the admin panel to change the text that appears for the "read more" link.
