### ISSUE TITLE
HTML entities not preserved

### ISSUE THREAD

**Issue by ghost** [ecj2/kaku#20]
If I edit a post and put & lt; in it, save it, then edit again, there's a < and not & lt;

**Comment by ecj2** [comment]
Commit c60ec27 should fix this. Let me know if the issue persists.

**Comment by ghost** [comment]
I commented on the patch, instead of here, oops. See the comment. Adding this after htmlentities fixes it:

```
$body = str_replace("&amp;#123;%", "{%", $body);
$body = str_replace("%&amp;#125;", "%}", $body);
```

it just replace the entities for {% and %} back.

**Comment by ecj2** [comment]
Thanks. I committed your fix (20abe7f).

**Comment by ecj2** [comment]
Actually, that "fix" causes another issue: the tag reference is lost in posts. This means editing a post with the contents of "My favorite color is {%favorite_color%}" becomes "My favorite color is blue" on the next edit. This, in turn, would lose the tag reference on subsequent edits. I think by calling `htmlentities()` _before_ encoding would fix both issues.

**Comment by ecj2** [comment]
Commit ff727d3 _should_ fix the encoding issue, all the while preserving tag references. Let me know otherwise.
